import plots

plots.selected_plots_one_experiment(
        plottitle = None,
        subplottitles=["Summed total Biases","State 1, Action Down","State 1, Action Left","State 6, Action Left","State 6, Action Down","empty","Summed total squared Biases","State 1, Action Down","State 1, Action Left","State 6, Action Left","State 6, Action Down"],
        plotlist = ["Mean bias metrics at evals","Mean Q function values at chosen at evals","empty","Mean bias metrics at evals","Mean special logs at evals","empty"],
        correct_action_log = True,
        focus_state_actions = True,
        bias_estimation = True,
        algo_special_logs = True,
        squared_normalized_best_arms_list = [[(False,False,False)],[(True,False,False)]],
        which = [[(1,2),(1,3),(6,3),(6,2)]],
        max_steps_per_epoch = -1,
        index = [[[],[],[3,4,24,23]]],
        input_path = "plots/.results_to_plot/grid_world_GridWorld.pkl",
        plot_folder = "plots",
        project_name = "paper",
        individual_figsize = (4,4),
        num_rows = 6,
        save_string = "Plot 1")

plots.selected_plots_one_experiment(
        plottitle = "Correct action rates, biases, and scores",
        subplottitles=["Policie's correctness rate\nat states 1,4,6, and 7","Correct action rates\nat epochs","Summed total Biases", "Summed total squared Biases","empty","Scores during evaluations", "Length of evaluations","Scores during epochs","Length of epochs"],
        plotlist = ["Mean correct action rates at chosen at evals","Mean correct action rates at epochs","Mean bias metrics at evals","empty","Mean scores at evals","Mean time of reaching terminal states at evals","Mean scores at epochs","Mean durations of epochs"],
        correct_action_log = True,
        focus_state_actions = True,
        bias_estimation = True,
        algo_special_logs = True,
        squared_normalized_best_arms_list = [[(False,False,False),(True,False,False)]],
        which = [[]],
        max_steps_per_epoch = -1,
        index = [[[],[],[]]],
        input_path = "plots/.results_to_plot/grid_world_GridWorld.pkl",
        plot_folder = "plots",
        project_name = "paper",
        individual_figsize = (4,4),
        num_rows = 5,
        save_string = "Plot 2.1")

plots.selected_plots_one_experiment(
        plottitle = "Q-function values and Sample variances next to fake goal",
        subplottitles=["State 1 Action Up", "State 1 Action Right", "State 1 Action Down","State 1 Action Left","empty","State 1 Action Up", "State 1 Action Right", "State 1 Action Down","State 1 Action Left","empty","State 4 Action Up", "State 4 Action Right", "State 4 Action Down","State 4 Action Left","empty","State 4 Action Up", "State 4 Action Right", "State 4 Action Down","State 4 Action Left","empty"],
        plotlist = ["Mean Q function values at chosen at evals","empty","Mean special logs at evals","empty","Mean Q function values at chosen at evals","empty","Mean special logs at evals","empty"],
        correct_action_log = True,
        focus_state_actions = True,
        bias_estimation = True,
        algo_special_logs = True,
        squared_normalized_best_arms_list = [[]],
        which = [[(1,0),(1,1),(1,2),(1,3)],[(4,0),(4,1),(4,2),(4,3)]],
        max_steps_per_epoch = -1,
        index = [[[],[],[1,2,3,4]],[[],[],[13,14,15,16]]],
        input_path = "plots/.results_to_plot/grid_world_GridWorld.pkl",
        plot_folder = "plots",
        project_name = "paper",
        individual_figsize = (4,4),
        num_rows = 5,
        save_string = "Plot 2.2")

plots.selected_plots_one_experiment(
        plottitle = "Q-function values and Sample variances stepping into the stochastic region",
        subplottitles=["State 6 Action Up", "State 6 Action Right", "State 6 Action Down","State 6 Action Left","empty","State 6 Action Up", "State 6 Action Right", "State 6 Action Down","State 6 Action Left","empty","State 7 Action Up", "State 7 Action Right", "State 7 Action Down","State 7 Action Left","empty","State 7 Action Up", "State 7 Action Right", "State 7 Action Down","State 7 Action Left","empty"],
        plotlist = ["Mean Q function values at chosen at evals","empty","Mean special logs at evals","empty","Mean Q function values at chosen at evals","empty","Mean special logs at evals","empty"],
        correct_action_log = True,
        focus_state_actions = True,
        bias_estimation = True,
        algo_special_logs = True,
        squared_normalized_best_arms_list = [[]],
        which = [[(6,0),(6,1),(6,2),(6,3)],[(7,0),(7,1),(7,2),(7,3)]],
        max_steps_per_epoch = -1,
        index = [[[],[],[21,22,23,24]],[[],[],[25,26,27,28]]],
        input_path = "plots/.results_to_plot/grid_world_GridWorld.pkl",
        plot_folder = "plots",
        project_name = "paper",
        individual_figsize = (4,4),
        num_rows = 5,
        save_string = "Plot 2.3")

plots.selected_plots_one_experiment(
        plottitle = "",
        subplottitles=["State 10 Action Up", "State 10 Action Right", "State 10 Action Down","State 10 Action Left","empty","State 10 Action Up", "State 10 Action Right", "State 10 Action Down","State 10 Action Left","empty","State 14 Action Up", "State 14 Action Right", "State 14 Action Down","State 14 Action Left","empty","State 14 Action Up", "State 14 Action Right", "State 14 Action Down","State 14 Action Left","empty"],
        plotlist = ["Mean Q function values at chosen at evals","empty","Mean special logs at evals","empty","Mean Q function values at chosen at evals","empty","Mean special logs at evals","empty"],
        correct_action_log = True,
        focus_state_actions = True,
        bias_estimation = True,
        algo_special_logs = True,
        squared_normalized_best_arms_list = [[]],
        which = [[(10,0),(10,1),(10,2),(10,3)],[(14,0),(14,1),(14,2),(14,3)]],
        max_steps_per_epoch = -1,
        index = [[[],[],[37,38,39,40]],[[],[],[50,51,52,53]]],
        input_path = "plots/.results_to_plot/grid_world_GridWorld.pkl",
        plot_folder = "plots",
        project_name = "paper",
        individual_figsize = (4,4),
        num_rows = 5,
        save_string = "Plot 2.4")